twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:  ['form/bootstrap_5_layout.html.twig']
    date:
        timezone: Europe/Paris
    globals:
        mangadex_url: '%mangadex_url%'
when@test:
    twig:
        strict_variables: true