twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:  ['bootstrap_4_layout.html.twig']
    date:
        timezone: Europe/Paris
    globals:
        mangadex_url: '%mangadex_url%'
        locales: "%app_locales_array%"
    paths:
        '%kernel.project_dir%/public/images/emails': emails