version: "3.7"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 33000:8080
    networks:
      - db
  dbPostgres:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hugo
      POSTGRES_PASSWORD: i9t5fp255
      POSTGRES_DB: projectDOC
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - volume-db:/var/lib/postgresql/data/pgdata
    networks:
      - db
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - "./public:/usr/src/app"
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 34000:80
    networks:
      - app
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - app
      - db
    volumes:
      - "./public:/usr/src/app/public"

volumes:
  volume-db:

networks:
  app:
  db:
