#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home_page:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    requirements:
        _locale: '%app_locales%'
    defaults:
        template: site/home_page.html.twig
        _locale: '%locale%'
